What is NumPy package for? Handlig numerical arrays

In [37]:
import numpy as np
np.__version__

'1.20.3'

In [ ]:
#For documentation run 
#np?

What is a python integer composed of?
ob_refcnt -> a reference count that helps python handle memory
ob_type -> variable type
ob_size -> size of the data members
ob_digit -> the actual integer value

In [6]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
type(L[0])

int

In [9]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [10]:
type(L2[0])

str

In [11]:
L3 = [True, '2', 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

NumPy arrays unlike python lists contain a single pointer to one block of data (similar to C language - where it points to a position in memory whose bytes encode the integer). Whilst a python list, each element is a pointer itself. Whilst its great because you can have multiple types in a list - its not efficient. 

Work around came up in 3.3 with the module array, which lets you create uniform type arrays

In [18]:
import array
A = array.array('i', L)
A
#note: i denotes the data type - in this case 'i' is for integer

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Whilst useful, NumPy's ndarray provide better workability.

In [19]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

NumPy arrays can only be ONE TYPE, if it does not match they will be upcast where possible. Data type can be specified with dtype attribute.

In [20]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [21]:
#Able to make a multi-demensional array
np.array([range(i, i+5) for i in [2,4,6]])

array([[ 2,  3,  4,  5,  6],
       [ 4,  5,  6,  7,  8],
       [ 6,  7,  8,  9, 10]])

In [22]:
#Create arrays filled with zeros
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
#Create an array defined by rows and colums filled with ones
np.ones((5,5), dtype=float)
#np.ones((row,colums), dtype = datatype)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
#Can also declare value to fill 
np.full((5,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [28]:
#You can create an array using the arange function which works similarly to the range()
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [35]:
#Create array of values evenly spaced - the last argument determines how many values for the array to have
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [39]:
#To make an array of uniformly distributed values 
np.random.random((3,3))

array([[0.7927575 , 0.29559748, 0.02105467],
       [0.43952555, 0.58384692, 0.93112616],
       [0.53921602, 0.72374912, 0.84037402]])

In [40]:
#Can also define an array that is normally distributed with define mean and standard deviation
np.random.normal(0,1,(3,3))

array([[-1.02403059, -0.69086197,  1.92878141],
       [-0.64675846, -0.68831275, -0.78836068],
       [ 0.13815798, -0.58525865,  0.25230064]])

In [41]:
#for random integers in an interval
np.random.randint(0,10,(3,3))

array([[9, 0, 6],
       [1, 6, 8],
       [0, 1, 0]])

In [42]:
#To make an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.empty(20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [46]:
#Array atributes
np.random.seed(0)
x1 = np.random.randint(10, size = 6)
print(x1)
x2 = np.random.randint(10, size=(3,4))
print(x2)
x3 = np.random.randint(10,size=(3,4,5))

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [56]:
print('Dimension of x3:',x3.ndim)
print('Size of x3:', x3.size)
print('Shape of x3:', x3.shape)
print('Data type:', x3.dtype)
print('Size of each element in bytes:', x3.itemsize)
print('Size of array in bytes:', x3.nbytes)

Dimension of x3: 3
Size of x3: 60
Shape of x3: (3, 4, 5)
Data type: int64
Size of each element in bytes: 8
Size of array in bytes: 480


Can access values using python index notation: x1[0] or for multidimensional separate dimensions with commas i.e. x2[0,0]
Likewise we can access subarray by using the samy python sintax x2[::-1, ::-1] -> reverses both rows and columns. x2[:2, :2] will show 0,1 row and column.

IMPORTANT DETAIL: Unlike in python lists, when we slice using NumPy arrays we are not getting a copy but rather a view. That means that whatever change made to the sliced array will also take place to the original array.

In [57]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [58]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [59]:
x2_sub[0,0] = 99
print(x2_sub)
print(x2)

[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Note how even though the change occured in x2_sub, the x2 array changed as well. To make a different space in memory use the copy() method.

In [60]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [61]:
x2_sub_copy[0,0] = 10
print(x2_sub_copy)
print(x2)

[[10  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Note how the original array did not change

#### Check point - Reshaping Arrays - 31/01

Place numbers 1-9 in a 3x3 grid

In [3]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


What does np.reshape(()) let you do?
Allows you to take an np.array and make it into a matrix by defining the # rows and # columns

In [7]:
x = np.array([1,2,3])
print(x)

[1 2 3]


In [ ]:
x.reshape((1,3))

What dooes np.newaxis do? It allows you to increase the dimension of an array by one depending where you put it  x[np.newaxis, :] means it will make it in the rows. Whereas x[:, np.newaxis] will make a new dimension in column.

In [9]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [10]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [12]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

How can you concatenate two arrays?

In [19]:
#Three ways
grid = np.array([[1,2,3],
                 [4,5,6]])
print(grid)

[[1 2 3]
 [4 5 6]]


In [21]:
#along the first axis (rows)
print(np.concatenate([grid,grid]))
#along the second axis (columns)
print(np.concatenate([grid,grid], axis = 1))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In the case the two np.arrays you're trying to concatenate have different dimension, use np.vstack (vertical stack) np.hstack(horizontal stack) or np.dstack (third dimension stack)

For splitting an np.array what can be used?

In [27]:
x =[1,2,3,4,5,6,7,8,9]
x1,x2,x3 = np.split(x,[3,5])
#Note the list inside the split is the indices of the split.
#Like in concatenate you can use np.vsplit(x,[]) np.hsplit(x,[]), np.dsplit(x,[])

Why do we prefer to use numpy?

Because it can be very fast when used with vectorized operations which can be implemented through universal functions (ufuncs).

What is a ufunc?

Functions which can be made to repeat calculations on array elements much more efficient.

Why can python be slow?
Because of its dynamic intepreted nature. This means it cant be compiled to more efficient C code or Fortran. 
What is the implementation of Python? CPython

Where is python slowness shown? When many small operations are repeated. Because CPython must check the type and function dispatch for every loop and many times for each element.

In [ ]:
#How can you time how long a function tkes to execute?
%timeit #followed by a functioncall

Ufunc are cool because instead of having to perform a loop that goes over every element and performs an operation we can simply use Ufunc's. These include all the basic arithmetic operations that you can perform on numbers.

Remember: the arithmetic operators are just wrappers for functions i.e. + is np.add()

In [34]:
#You can also perform absolute value 
x = np.arange(-10, 0)
print(x)
print(np.abs(x))
#bit irrelevant but worth knowing this also works with complex data

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]
[10  9  8  7  6  5  4  3  2  1]


In [35]:
#How can you make an array of angles?
np.linspace(0, np.pi, 3)

array([0.        , 1.57079633, 3.14159265])

In [ ]:
#Can also perform trigonometric functions as ufuncs
np.sin()
np.cos()
np.tan()
#AND INVERSE TRIGONOMETRIC FUNCTIONS
np.arcsin()
np.arccos()
np.arctan()
#and base 2 log, base 10 log, and natural log
np.log2()
np.log10()
np.log
#and use the values of the np as exponents
np.exp() #e^(whatever in parenthesis)
np.exp2() #2^
np.power(3,) #3^(whatever after comma)

#### Checkpoint Specialized ufuncs 03/02